# Generated by Django 2.0.2 on 2018-04-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsmbEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pcba_rev', models.CharField(max_length=2)),
                ('pcb_rev', models.CharField(max_length=2)),
                ('pcba_sn', models.PositiveIntegerField(unique=True)),
                ('osc_sn', models.PositiveIntegerField(unique=True)),
                ('gnss_sn', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('man_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finished_time', models.DateTimeField()),
                ('finisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisher_id', to='warehouse.Manufacturer')),
                ('starter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_id', to='warehouse.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sw_ver', models.CharField(max_length=100)),
                ('timing_sys', models.CharField(max_length=100)),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=5)),
                ('current', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Versa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.PositiveIntegerField(unique=True)),
                ('model_num', models.CharField(max_length=9)),
                ('work_order', models.PositiveIntegerField()),
                ('sale_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='testentry',
            name='versa_sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_versa_sn', to='warehouse.Versa', to_field='sn'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='warehouse.TaskType'),
        ),
        migrations.AddField(
            model_name='task',
            name='versa_sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_versa_sn', to='warehouse.Versa', to_field='sn'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='manufacturer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_type_id', to='warehouse.ManufacturerType'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asmbentry',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='warehouse.Task'),
        ),
        migrations.AddField(
            model_name='asmbentry',
            name='versa_sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asmb_versa_sn', to='warehouse.Versa', to_field='sn'),
        ),
    ]
