# Generated by Django 2.0.2 on 2018-04-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type_id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('0', 'No Task'), ('1', 'Assemble'), ('2', 'Program'), ('3', 'Test')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finisher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finisher_id', to='warehouse.Manufacturer'),
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
