# Generated by Django 2.0.2 on 2018-04-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20180416_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finisher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finisher_id', to='warehouse.Manufacturer'),
        ),
    ]
