# Generated by Django 2.0.2 on 2018-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20180416_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_type',
            field=models.CharField(choices=[('0', 'default'), ('1', 'Assemble'), ('2', 'Program'), ('3', 'Test')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('0', 'default'), ('1', 'Assemble'), ('2', 'Program'), ('3', 'Test')], default='0', max_length=1),
        ),
        migrations.DeleteModel(
            name='ManufacturerType',
        ),
    ]
