# Generated by Django 2.0.2 on 2018-04-16 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20180416_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='finisher_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_ender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='starter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_starter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
