# Generated by Django 2.0.2 on 2018-04-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0005_auto_20180416_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finisher_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='starter_id',
        ),
        migrations.AddField(
            model_name='task',
            name='finisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_ender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_starter', to=settings.AUTH_USER_MODEL),
        ),
    ]
