# Generated by Django 2.0.2 on 2018-04-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20180417_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sw_ver', models.CharField(max_length=100)),
                ('timing_sys_ver', models.CharField(max_length=100)),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=5)),
                ('current', models.DecimalField(decimal_places=3, max_digits=4)),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prog_task_id', to='warehouse.Task')),
                ('versa_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_versa_sn', to='warehouse.Versa', to_field='sn')),
            ],
        ),
        migrations.RemoveField(
            model_name='testentry',
            name='versa_sn',
        ),
        migrations.AlterField(
            model_name='asmbentry',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asmb_task_id', to='warehouse.Task'),
        ),
        migrations.DeleteModel(
            name='TestEntry',
        ),
    ]
